version: '3'

services:
  gjango:
    build:
      context: .
      dockerfile: dockerfile-gjango
    
    command: gunicorn -b :8800 meusite.wsgi
    volumes:
      - .:/usr/src/
    ports:
      - "80:8800"
