version: '3'

services:
  gjango:
    build:
      context: .
      dockerfile: dockerfile-gjango
    command: gunicorn --bind=unix:/usr/sock/gunicorn.sock meusite.wsgi
    volumes:
      - ./src:/usr/src/
      - sock:/usr/sock/
#    depends_on:
#      - mdb

  mdb:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: senharoot
      MYSQL_DATABASE: nomedb
      MYSQL_USER: nomeusua
      MYSQL_PASSWORD: senhausua

  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./src/static/:/usr/share/nginx/static/
      - ./letsencrypt/:/etc/nginx/letsencrypt/
      - sock:/etc/nginx/sock/
    depends_on:
      - gjango

volumes:
  sock:
