version: '3'

services:
  gjango:
    build:
      context: .
      dockerfile: dockerfile-gjango
    command: gunicorn --bind=unix:/gunicorn.sock meusite.wsgi
    volumes:
      - .:/usr/src/
    environment:
      - VIRTUAL_HOST=aa.forense.cf
      - LETSENCRYPT_HOST=aa.forense.cf
      - VIRTUAL_PORT=8000
    expose:
      - "8000"

  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

#networks:
#  default:
#    external:
#      name: nginx-proxy
