version: '3'

services:
  gjango:
    build:
      context: .
      dockerfile: dockerfile-gjango
    command: gunicorn --bind=unix:/usr/src/sock/gunicorn.sock meusite.wsgi
    volumes:
      - .:/usr/src/

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./sock/:/etc/nginx/sock/
      - ./static/:/usr/share/nginx/static/
    depends_on:
      - gjango
